version: "3"
services:
      frontend:
          build: 
            context: ./habatu-frontend
            dockerfile: Dockerfile.dev
          volumes:
          - ./habatu-frontend:/usr/app
          - /usr/app/node_modules
          environment:
            - VUE_APP_FRONTEND_HOST=http://localhost:8080
            - VUE_APP_BACKEND_HOST=http://localhost:8000
          ports:
            - '8080:8080'
      habatu-backend:
           build:
            context: ./habatu-backend
            dockerfile: Dockerfile.dev
           volumes:
            - ./habatu-backend:/usr/app
            - /usr/app/node_modules
           command: npm run dev
           environment:
            - TOKEN_KEY=MUWU4l!I5#lRN%YPTQJ&2p@9b6E89#fJ
            - NODE_ENV=production
            - ADMIN_NICKNAME=archi
            - ADMIN_PASSWORD=*6y!1XIt73%7
            - CLEAR_ON_STARTUP=false
            - PORT=8000
            - ALLOWED_HOST=*
            - MONGO_USERNAME=ygbydmzfnfvbxbmqdqmy
            - MONGO_PASSWORD=bQCrPwf2DTc7Wvm2XFT9
           ports:
             - "8000:8000"
           links:
             - mongo
      mongo:
            container_name: mongo
            image: mongo
            volumes:
              - data:/data/db
            ports:
              - '27018:27017'
            environment:
              MONGO_INITDB_ROOT_USERNAME: ygbydmzfnfvbxbmqdqmy
              MONGO_INITDB_ROOT_PASSWORD: bQCrPwf2DTc7Wvm2XFT9
      mongo-express:
            image: mongo-express
            restart: always
            ports:
              - 8081:8081
            environment:
              ME_CONFIG_MONGODB_URL: mongodb://ygbydmzfnfvbxbmqdqmy:bQCrPwf2DTc7Wvm2XFT9@mongo:27017/
              ME_CONFIG_BASICAUTH_USERNAME: AZc8A7es3vNQAmJs5e8c
              ME_CONFIG_BASICAUTH_PASSWORD: HGxTz9juPHuND55h8ztB
volumes:
  data:
