version: "3"
services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/deploy/nginx.conf:/etc/nginx/nginx.conf
          - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
          - habatu-frontend
          - habatu-backend
        links:
          - habatu-frontend
          - habatu-backend
      habatu-backend:
           build: ./habatu-backend
           restart: unless-stopped 
           volumes:
            - ./habatu-backend:/usr/app
            - /usr/app/node_modules
           environment:
            - TOKEN_KEY=MUWU4l!I5#lRN%YPTQJ&2p@9b6E89#fJ
            - NODE_ENV=production
            - ADMIN_NICKNAME=archi
            - ADMIN_PASSWORD=*6y!1XIt73%7
            - PORT=8000
            - ALLOWED_HOST=*
           links:
             - mongo
      habatu-frontend:
          build: ./habatu-frontend
          
      mongo:
            container_name: mongo
            image: mongo
            restart: unless-stopped 
            volumes:
              - data:/data/db
            ports:
              - '27018:27017'
      mongo-express:
            image: mongo-express
            restart: always
            ports:
              - 8081:8081
            environment:
              ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
volumes:
  data: