version: "3"
services:
      nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
          - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
          - habatu-frontend
          - habatu-backend
        links:
          - habatu-frontend
          - habatu-backend
      habatu-backend:
           build: ./habatu-backend
           restart: unless-stopped 
           volumes:
            - ./habatu-backend:/usr/app
            - /usr/app/node_modules
           environment:
            - TOKEN_KEY=MUWU4l!I5#lRN%YPTQJ&2p@9b6E89#fJ
            - NODE_ENV=production
            - ADMIN_NICKNAME=archi
            - ADMIN_PASSWORD=*6y!1XIt73%7
            - PORT=8000
            - ALLOWED_HOST=*
            - MONGO_USERNAME=ygbydmzfnfvbxbmqdqmy
            - MONGO_PASSWORD=bQCrPwf2DTc7Wvm2XFT9
           links:
             - mongo
      habatu-frontend:
          build: ./habatu-frontend
          restart: unless-stopped
          
      mongo:
            container_name: mongo
            image: mongodb-raspberrypi4-unofficial-r7.0.14
            restart: unless-stopped
            volumes:
              - data:/data/db
            ports:
              - '27018:27017'
            environment:
              MONGO_INITDB_ROOT_USERNAME: ygbydmzfnfvbxbmqdqmy
              MONGO_INITDB_ROOT_PASSWORD: bQCrPwf2DTc7Wvm2XFT9
      mongo-express:
            image: mongo-express
            restart: always
            ports:
              - 8081:8081
            environment:
              ME_CONFIG_MONGODB_URL: mongodb://ygbydmzfnfvbxbmqdqmy:bQCrPwf2DTc7Wvm2XFT9@mongo:27017/
              ME_CONFIG_BASICAUTH_USERNAME: AZc8A7es3vNQAmJs5e8c
              ME_CONFIG_BASICAUTH_PASSWORD: HGxTz9juPHuND55h8ztB
volumes:
  data: