version: "3"
services:
      nginx:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./nginx/deploy/nginx.conf:/etc/nginx/nginx.conf
          - /etc/letsencrypt:/etc/letsencrypt
      habatu-backend:
          build: ./habatu-backend
          volumes:
          - ./habatu-backend:/usr/app
          - /usr/app/node_modules
          command: node index.js
          environment:
          - TOKEN_KEY=MUWU4l!I5#lRN%YPTQJ&2p@9b6E89#fJ
          - NODE_ENV=production
          - ADMIN_NICKNAME=archi
          - ADMIN_PASSWORD=*6y!1XIt73%7
          - ALLOWED_HOST=https://habatu.wildert.ch
          - PORT=8000
          links:
            - mongo
      mongo:
            container_name: mongo
            image: mongo
            volumes:
              - ./data:/data/db
            ports:
              - '27018:27017'