version: "3"
services:
      frontend:
          build: 
            context: ./habatu-frontend
            dockerfile: Dockerfile
          volumes:
          - ./habatu-frontend:/usr/app
          - /usr/app/node_modules
          - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
          ports:
            - '80:80'
      habatu-backend:
           build: ./habatu-backend
           volumes:
            - ./habatu-backend:/usr/app
            - /usr/app/node_modules
           command: node index.js
           environment:
            - TOKEN_KEY=<top secret>
            - NODE_ENV=production
            - PORT=8000
            - ALLOWED_HOST=*
           ports:
             - "8000:8000"
           links:
             - mongo
      mongo:
            container_name: mongo
            image: mongo
            volumes:
              - ./data:/data/db
            ports:
              - '27018:27017'